name: build

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    - uses: nuget/setup-nuget@v1
      with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: 'latest'
    - run: nuget restore visual-studio-git.sln
    - uses: microsoft/setup-msbuild@v1.0.2
    - run: MSBuild.exe $Env:GITHUB_WORKSPACE\visual-studio-git\visual-studio-git.csproj -p:Configuration=Release
      timeout-minutes: 5
